# Generated by Django 5.2.8 on 2025-11-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=65, verbose_name='Titulo da tarefa')),
                ('descrição', models.CharField(max_length=165, verbose_name='Descrição da tarefa')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Finalizado', 'Finalizado')], default='Pendente')),
            ],
        ),
    ]
