# Generated by Django 5.2.8 on 2025-11-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_category_todo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='todo',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='todo_list.category'),
        ),
    ]
